fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "mysql":
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
      ref:  'origin/0.x'
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "sysctl": "git://github.com/duritong/puppet-sysctl.git"
    "rabbitmq":
      repo: "git://github.com/puppetlabs/puppetlabs-rabbitmq"
      ref: 'origin/2.x'
    "inifile":  "git://github.com/puppetlabs/puppetlabs-inifile"
    "qpid": "git://github.com/dprince/puppet-qpid.git"
    "postgresql": "git://github.com/puppetlabs/puppet-postgresql.git"
  symlinks:
    "cinder": "#{source_dir}"
