name    'puppetlabs-cinder'
version '2.0.0'
source  'https://github.com/stackforge/puppet-cinder'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Cinder Module'
description  'Puppet module to install and configure the Openstack Cinder block storage service'
project_page 'https://launchpad.net/puppet-openstack'

dependency 'cprice404/inifile', '>= 0.10.3'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/stdlib', '>= 2.5.0'
dependency 'puppetlabs/rabbitmq', '>= 2.0.2'
dependency 'dprince/qpid', '>= 1.0.0'
